[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "consulsync"
version = "0.0.1"
requires-python = ">= 3.11"
dependencies = []

[project.scripts]
consulsync = "consulsync:doCli"
